### ISSUE TITLE
Can't use the live preview with minted package

### ISSUE THREAD

**Issue by Pacane** [xuhdev/vim-latex-live-preview#1]
See this: http://tex.stackexchange.com/questions/81958/using-vim-latex-live-preview-with-minted-package

**Comment by AndreaGiardini** [comment]
Sorry to bring up this super old bug again, but i just had the same problem and the suggestion of @xuhdev worked like a charm... i replaced the tmp_directory with the currect directory of my latex project and everything worked perfectly.

Should i PR it?

**Comment by xuhdev** [comment]
@AndreaGiardini Definitely! Can you make `tmp_dir` be a customizable dir? Thanks!

**Comment by AndreaGiardini** [comment]
Why not using the project folder itself? is there any particular reason?

**Comment by xuhdev** [comment]
@AndreaGiardini I don't remember the exact reason, but it seems that there may be some conflict for the PDF files in the current directory if the current directory is in use. What we can do is to switch the default to the current directory to avoid issues mentioned this thread, but allow users to use a tmp dir.

**Comment by AndreaGiardini** [comment]
Thank you for the clarification :) i will do it!

**Comment by xuesoso** [comment]
Tried to preview a tex file with minted and it's not working. What is a proper way to define current working directory as the temp_dir as a work around?
