### ISSUE TITLE
vim dissapears

### ISSUE THREAD

**Issue by sudo-ghost** [xuhdev/vim-latex-live-preview#101]
## Expected behavior
when i used it with I3 it works perfectly fine and spawns the zathura window right next to the vim window. but in dwm for some reason the zathura window will spawn its its like it spawns on top of the vim window and i can only get back to the vim window after closing the zathura window.
Tell us what should happen

## Actual behavior
it will spawn the zathura window but gets rid of the vim window 
Tell us what happens instead

## Steps to reproduce
the steps to reproduce it are to just run the plugin. im not sure if im the only one who has had this issue or not so if there is a similar issue please link me it.

## System configuration

- **Vim version**:
8.2
- **Platform**:
Arch

![this dumb shit](https://user-images.githubusercontent.com/57652105/80856167-80b88680-8c15-11ea-93df-af0063459d30.gif)

**Comment by sudo-ghost** [comment]
i know the gif isnt high quality but this is what im talking about. the zathrua window just overlaps the vim window for some reason

**Comment by camr12** [comment]
Getting the same issue.

**Comment by sudo-ghost** [comment]
So a temporary fix I found was actually to use tmux when using this. That does not mean this issue is resolved though. I have been trying to get this working normally for a while to no avail

**Comment by sudo-ghost** [comment]
so i actually figured out that it had to do with my terminal getting swallowed by launched programs. ill close this issue now
