### ISSUE TITLE
[solved] E492: Not an editor command: LLPStartPreview ->[Bug]

### ISSUE THREAD

**Issue by xradiation** [xuhdev/vim-latex-live-preview#105]
## Expected behavior

- Obiously this is supposed to show the tex file privew

## Actual behavior
- The following error message : 
`E492: Not an editor command: LLPStartPreview`

## Steps to reproduce
- Execute : 
`:LLPStartPreview`

## System configuration

- Neovim : NVIM v0.5.0-592-ga695da7d3 (AUR)
- pynvim : installed
- has('python3') : 1
- has('python') : 0
- `:script` output :  `vim-latex-live-preview` is nowhere to be seen ( not loaded )

can you guys please list `vim-latex-live-preview` python deps, since i suspect the issue to be related to a missing dep, any help is much appreciated.

And just as a side note : 
I've already read the main plugin README and the related issue

- " See issue #12, provided the plugin is correctly installed, this is likely a Python issue. "

and it seems that the suggested fix is aleardy implemented i.e to substitue every `python` occurence with `python3` so thats not the issue in my case.

why am saying that this is supposed to be a python package related issue, is because I've recently cleaned the `~/.local/lib/python3.8/site-packages/` ( the `site-packages` root dir is completly clean so nothing messing there at least ) and I've done a backup of the entire thing however it's kind of missed up for now so there is no way to test every single package; and this brings me to the my request : 

- can any of the devs list ( if possible that is ) the python dependencies for the plugin so that i can work out what exactly is messing ?
again really appreciate any help whatsoever .

**Comment by xradiation** [comment]
I've solved the issue and it wasn't really related to a missing module, since I've checked every `import` (`os, subprocess...`) in the plugin and all worked just fine except for `import vim` which I guess is supposed to be executed by vim, any way after some fiddling around with `.vimrc` ( linked to `init.vim` ), reinstalling `neovim-git` and `python-neovim`.

 I've found out that the issue was in the ` Plug 'xuhdev/vim-latex-live-preview', { 'for': 'tex' } ` for some reason ` , { 'for': 'tex' } ` kind of hanged the plugin from starting at all which i thought was weird, but after removing that part the plugin got loaded fine .

One other issue is that I have `Window Swallowing` turned on on my terminal emulator, which makes the pdf preview window sit on top of the vim window when started, does any one know how workaround that some how ? 
- since i consider it to be a bug please take a look into it @xuhdev, many thanks.

**Comment by Abdulee** [comment]
This really helped me to get LLP working on my nvim setup. Thank you very much

**Comment by 9-k** [comment]
Just checking - the file needs to end in .tex for the editor command to be valid. That fixed the issue for me.
