### ISSUE TITLE
Feature Request: local tex and bib engines

### ISSUE THREAD

**Issue by CantoroMC** [xuhdev/vim-latex-live-preview#111]
Allow to specify tex engine locally with:
% !TeX program = ... 
which is also supported by Texworks

and additionally also the bib engine with something like
% !Tex bib =

In my opinion it would be more comfortable that changing vim global variables

**Comment by badouralix** [comment]
Hi @CantoroMC ! That seems to be a really good idea, thanks !
I'll set a label here for now so that the issue gets some traction, and hopefully I can free some time to look into it

**Comment by CantoroMC** [comment]
Thanks for the positive feedback.
I find this plugin really good, it runs smoothly and have a very important, in my opinion, characteristic for a vim plugin, it does just one thing.

**Comment by hammondm** [comment]
Hi

That would be perfect!

:)

mh
