### ISSUE TITLE
LLPStartPreview doesn't start

### ISSUE THREAD

**Issue by linuscl** [xuhdev/vim-latex-live-preview#12]
```
Error in "function <SNR>34_Compile":
Line   10:
```

That's the error I received, and evince (pdf viewer) says that it cannot find the pdf file.

**Comment by paynito** [comment]
starting $vim main.tex    after enabling your plugin in .vimrc.
`Error detected while processing function <SNR>28_Initialize:
line   10:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.`

**Comment by xuhdev** [comment]
@paynito This is because your Vim installation does not have Python feature enabled (or the python feature is broken). Please try to reinstall Vim. You can search for E887 online, the solution is the same, regardless of the plugin.

**Comment by kenoph** [comment]
I just want to add that I have VIM compiled with python3 and it seems that I have to `:%s/python/python3/g` on my xenial machine.

**Comment by luchaoo7** [comment]
Hello does anyone know why when I type :LLPStartPreview in VIM it says "Not an editor command"

**Comment by xuhdev** [comment]
@luchaoo7 You probably didn't have the plugin loaded. You can check by running `:script`.

**Comment by luchaoo7** [comment]
@xuhdev thanks for your reply, it is loaded. could it have to do with the tags? 
The only tag I see in  ~/.vim/bundle/vim-latex-live-preview/doc/tag is  "vim-latex-live-preview.txt"   

In the "latexlivepreview.vim" file on line  command!  184 is the following:
command! LLPStartPreview call s:StartPreview()   

I can't seem to spot why its not working.

**Comment by xuhdev** [comment]
As long as it's loaded, it should be available. Tags are just indices for quick lookup. Perhaps you wanna check your typing of the command?

**Comment by jestin** [comment]
I'm seeing the same thing.  `script` says that it is loaded:

`~/.config/vim/plugged/vim-latex-live-preview/plugin/latexlivepreview.vim`

but vim's command autocomplete doesn't pick it up, and I get `Not an editor command: LLPStartPreview`.

As you can see, I installed this using the vim-plug plugin manager, but I hope that isn't the issue.

**Comment by kunlilin2991** [comment]
I have encounter the same problem 
I use vundle to manage plugin 
in vimrc 
Plugin 'xuhdev/vim-latex-live-preview' 
the info in vim :script is as following 
 77: ~/.vim/bundle/vim-latex-live-preview/plugin/latexlivepreview.vim
however when i type LLPStartPreview
this problem appeared as following 
E492: not an editor command :LLPStartPreview
this pluginin seems not work.

**Comment by badouralix** [comment]
@kunlilin2991 thanks for the feed back !
`vundle` doesn't seem to be the issue (a section to the readme should be added about that actually)

Could you provide some info about your system and your vim ? Also, what does `:echo g:loaded_vim_live_preview` output ?

**Comment by vicentius** [comment]
Having the same problem here. VIM 8.0 installed on macOS Sierra through Homebrew, relevant features: +python3 -python.
Plugin installed through vundle. Configured the previewer and the updatetime as per the instructions. 
Doing `:echo g:loaded_vim_live_preview` returns 1.

Happy to provide more info for further investigation.

**Comment by ranguli** [comment]
Also having the same issue as @vicentius, @kunlilin2991, @luchaoo7 and @jestin. ```:script``` is saying the plugin is in fact being loaded, but ```:LLPStartPreview ``` with _or_ without a filename returns the ``` E492: Not an editor command: LLPStartPreview ```.

I'm running Xubuntu 16.04, with Vim 7.4 compiled with support for +python and +python3

**Comment by badouralix** [comment]
Thanks @vicentius for the python3 checking! Then this should be easy to fix. Otherwise, maybe we can look for a way to get rid of python and only use vim internal functions...

@ranguli @kunlilin2991 : digging into `E492`, I found this post <https://github.com/VundleVim/Vundle.vim/issues/486#issuecomment-193898540>. Could you check whether our issue is somehow related to this one? If so, it can be fix using a [_.gitattributes_ file](https://help.github.com/articles/dealing-with-line-endings/).

**Comment by ranguli** [comment]
@vicentius Thanks for this. Lots of interesting points brought up in that thread, personally (and for future reference) the later output of ```:version``` for me returns:
```
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"  
```
Where ```$VIM``` is seemingly undefined. _Furthermore_, there's no vimrc actually present in ```/~.vim/vimrc```. What this has to do with our issue, maybe nothing, but something to keep in mind in case we hit a dead end. It shouldn't be confusing my ```~/.vimrc``` with the ```~/.vim/vimrc``` if the latter doesn't really exist. 

I tried running the ```git config --global core.autocrlf input``` as recommended in the plugin directory and it didn't change anything. 

For someone reading this in the future, VundleVim/Vundle.vim#492
may could also be your problem as well, just not in our case specifically.

I also tried this suggestion in VundleVim/Vundle.vim#486
```  set rtp+=$HOME/.vim/bundleVundle.vim ``` 
Where ```$HOME``` used to be ```~```, also with no luck. 

There's a chance it would work if I followed the suggestion from the above thread, of re-installing Vundle, but for end users it will likely be more appealing if they don't have to do so. In which case moving away from Python and towards Vim script for those tasks sounds like the best option.

**Comment by ranguli** [comment]
Regarding @vicentius's suggestion of changing the instances of ```python``` to ```python3```, I couldn't get it to work for me personally, but the following happened.

```if (!has('python') . . .) ``` will throw the error  ```E492: Not an editor command: LLPStartPreview ```

However,  ``` if(!has('python3') . . .)``` will throw  ```Failed to compile```

**Comment by vicentius** [comment]
`Failed to compile` is a big step ahead. That means the external python calls worked, but the selected tex engine failed to compile your document. You now have something else to debug / investigate :)

**Comment by ranguli** [comment]
Nice. All that was required to resolve ```Failed to compile``` was just supplying a proper LaTeX document, of course! The fix has worked for @vicentius and I, but I couldn't speak to whether or not this would add any regressions. I can make a pull request of my changes and we can go from there with any kind of adjustments it may need.

And for future reference, the issue of vim picking up a second .vimrc file seemed to be an unrelated thing, as did the effect of the git command (both documented above).

**Comment by badouralix** [comment]
Cool! Cool cool cool! So for now, let's get a fix to support both `+python` and `+python3`, and we'll see later for maybe avoiding using python. @vicentius please go ahead 😃

And also, we absolutely need to get some decent debug info, because the current way of investigation is crazy hard...

**Comment by ranguli** [comment]
It sounds like supporting both ```+python``` and  ```+python3``` will remove support for Debian-based systems.

**Comment by ranguli** [comment]
> And also, we absolutely need to get some decent debug info, because the current way of investigation is crazy hard...

Is this the same as #34? I agree, I think in trying to accomplish this we may need a better understanding of what's actually happening. I might try and try improve documentation too, as I haven't taken a good solid look at the script and could personally benefit from better docs.

**Comment by badouralix** [comment]
> It sounds like supporting both `+python` and `+python3` will remove support for Debian-based systems, according to [this](https://stackoverflow.com/questions/23023783/vim-compiled-with-python-support-but-cant-see-sys-version) StackOverflow thread, that I found [here](https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source).

As far as I understand, as long as one gets a working vim with python features enable, a vimscript can dynamically dispatch calls to python. For instance [plug.vim#1341](https://github.com/junegunn/vim-plug/blob/88cc9d78687dd309389819f85b39368a4fd745c8/plug.vim#L1341)

---

Another issue: as you were talking about debian-based systems, I took a look at the features embedded in the latest vim package in debian. It comes with `-python` and `-python3`... 😢 

Btw, to test multi-platforms, I go with [docker](https://en.wikipedia.org/wiki/Docker_(software)). But we can also set up [vader tests](https://github.com/junegunn/vader.vim) to run on [travis](https://travis-ci.org/).

**Comment by ranguli** [comment]
> As far as I understand, as long as one gets a working vim with python features enable, a vimscript can dynamically dispatch calls to python. For instance plug.vim#1341

Okay, nice! So the check to see if ```python``` is installed [here](https://github.com/xuhdev/vim-latex-live-preview/blob/master/plugin/latexlivepreview.vim#L31) needs to be expanded for both versions, then the reference to ```python``` throughout the rest of the code needs to also be changed dynamically, as in my case it only works as ```python3```

> Another issue: as you were talking about debian-based systems, I took a look at the features embedded in the latest vim package in debian. It comes with -python and -python3... :cry:

Ouch, so it sounds like we can just accept the fact that users will need to compile Vim with Python support, which isn't that bad seen as how other plugins require this step too. 

Setting up tests to run on Travis will be super nice. I'll add Vader and a Testing section to the README. If the dockerfiles have anything of interest feel free to track them, just to keep things uniform.

**Comment by kunlilin2991** [comment]
Sorry to reply so late, I use ubuntu 16.04 with vim 8.0 and enable both python and python3, also, there is only one .vimrc file in my computer. what information can I offer about vim and plugin to solve the bug?

**Comment by ranguli** [comment]
@kunlilin2991 Pasting the output of ```:version``` and ```:script``` should be everything we'd need!

**Comment by kunlilin2991** [comment]
For me the --version is list in following, ~/.vim/vimrc is not actually exit. 
#`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  8 2017 13:53:46)
Included patches: 1-596
Compiled by kunlynn
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      +xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     +xpm
+emacs_tags      -mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl    -ldl       -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
`
the \:script is list as following 
` 77: ~/.vim/bundle/vim-latex-live-preview/plugin/latexlivepreview.vim`

**Comment by kunlilin2991** [comment]
the \:script is list as following 
` 77: ~/.vim/bundle/vim-latex-live-preview/plugin/latexlivepreview.vim`

and the version about python and vimrc file is list as following:
` +python/dyn  
 +python3/dyn 
`
I also have two vimrc list as following 
`   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
`
for the 2nd file, it does not exit.

**Comment by masroorrasheed** [comment]
I edited my all "python" instances to "python3" in ~/.vim/bundle/vim-latex-live-preview/plugin/latexlivepreview.vim. The preview worked.

**Comment by xuhdev** [comment]
I think we need to allow for customizing python version in this case...

**Comment by xuhdev** [comment]
@badouralix This fix actually might cause some issues. The reason is that, as long as either `python` or `python3` is initialized, the other one cannot. Therefore, if some other plugins relies on `python`, but we initialize `python3`, we will break them. Same thing happens in the other way around.

**Comment by badouralix** [comment]
I couldn't make things break. In all my tests, I was able to use both `python` and `python3`, whenever `vim-llp` was loaded or not.
The reason I believe this fix works is that this `py_exe` trick is actually used in [plug.vim#L1341](https://github.com/junegunn/vim-plug/blob/88cc9d78687dd309389819f85b39368a4fd745c8/plug.vim#L1341), and such an issue would have been reported long time ago with this plugin. Nonetheless, just to be sure, we can switch test for `python` before test for `python3`.

**Comment by D0048** [comment]
Encountering the same here. Could anyone help? 
Doing :echo g:loaded_vim_live_preview returns 1.

**Comment by bmikaili** [comment]
Why is this closed? I still get this.

**Comment by ylatex** [comment]
Hi, guys
today i install this plugin in my mac, but it can not work, which always prompt "fail to compile". could you help me to solve this issue?

**Comment by Nillerh** [comment]
> Hi, guys
> today i install this plugin in my mac, but it can not work, which always prompt "fail to compile". could you help me to solve this issue?

Probably just a latex syntax error. Try compile a latex example.

**Comment by mtoohey31** [comment]
Sorry to comment on an old closed issue like this, but I thought I should leave what I found somewhere on this repo. For me, I was also experiencing this error, but in my case, the solution to the problem was to uninstall the `mactex-no-gui` cask and install the normal `mactex` cask instead.

**Comment by DaveAlsina** [comment]
I'm using Manjaro and the reason why it wasn't working for me was because I forgot to install latex compiler, hope you are not in the same situation haha check: https://archlinux.org/groups/x86_64/texlive-most/
