### ISSUE TITLE
"python is required" when attempting to load plugin

### ISSUE THREAD

**Issue by reDpz** [xuhdev/vim-latex-live-preview#127]
## Expected behavior

Plugin should load

## Actual behavior

I get an error telling me that "python is required"

## Steps to reproduce

Tell us how it occurs

1. load plugin

## System configuration

- **neovim version**:

```bash
# output of `nvim --version`
```
```
❯ nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- **Platform**:
Artix linux x86_64

Python is installed
![image](https://user-images.githubusercontent.com/71374038/232228558-67a43fd2-6f6c-40f5-95ed-26203b8a42dc.png)

**Comment by reDpz** [comment]
forgot to include screenshot of the error itself sorry,
![image](https://user-images.githubusercontent.com/71374038/232228963-37ac05a6-4c25-494b-b817-64c4c802fda7.png)
![image](https://user-images.githubusercontent.com/71374038/232228972-4be63ed1-5cc0-49ec-be21-b0e9cb7d4495.png)

**Comment by xuhdev** [comment]
It's not about whether Python is installed. Your vim must be built with the Python feature. You can check this by running `:version` within your Vim. Check out this image here: https://vi.stackexchange.com/questions/10242/vim-8-0-python-support

**Comment by reDpz** [comment]
yeah I figured out that this was an nvchad problem not a problem for this repo sorry I'll close this issue
