### ISSUE TITLE
Auto refresh doesn't work on bib files

### ISSUE THREAD

**Issue by liyi-david** [xuhdev/vim-latex-live-preview#13]
The tool is really impressive and helpful for me. However, I've checked the source code and find that when I save a source file, only this file itself is updated. So if I edit the bib files, the corresponding modification would not appear in the preview. Is that correct or I'm using a wrong configuration?

**Comment by xuhdev** [comment]
This is a limitation of this plugin (sorry!). You can use `latexmk -pvc` though, if it's acceptable for you.

**Comment by paynito** [comment]
I'm confused, run `latexmk -pvc` from the terminal, or use that instead of the line `g:livepreview_previewer = 'open -a Skim'`?

**Comment by xuhdev** [comment]
@paynito From terminal. Then open the pdf file with Skim. The `latexmk` program will recompile every time when you save the tex file.
