### ISSUE TITLE
Not showing the preview

### ISSUE THREAD

**Issue by mjonyh** [xuhdev/vim-latex-live-preview#17]
![screenshot](https://cloud.githubusercontent.com/assets/6975114/13704144/a27dea3e-e7c4-11e5-9dc6-26c0f6e3f4f0.png)

I don't know why it is not showing! No errors reported. Just not showing! My setup works well with Ubuntu 15.10. Currently I am using archlinux. Previewer is set to use "zathura". But it works well with "evince"!

**Comment by xuhdev** [comment]
what pdf viewer did you use?

**Comment by mjonyh** [comment]
"zathura" pdf viewer is not working. but "evince" pdf viewer works fine.

**Comment by xuhdev** [comment]
@mjonyh This plugin can only automatically recompile the tex file. The output pdf file would keep changing to be up to date. Unfortunately some pdf viewers cannot auto refresh when the pdf file changes. Maybe you should report the bug to zathura: auto reload when the underlying pdf file changes.
