### ISSUE TITLE
Ubuntu 16.04: Not recognized and/or freezing the system

### ISSUE THREAD

**Issue by RJ-Russell** [xuhdev/vim-latex-live-preview#19]
I had this this installed on Ubuntu 14.04 and it worked perfectly. Now that I have 16.04 I have it installed on two systems.
System 1: On a virtual box (Win10 host, Ubuntu 14.04 guest), plugin freezes the system, and I have to reboot in order to free the system. When I remove the plugin, there are no issues.

System 2: Ubuntu 16.04 installed. The command :LLPStartPreview is not even recognized within vim.

Both systems have vim-gtk installed.

As I stated previously, when I was running 14.04 there was no issues. I am assuming there is a compatibility issue with the new 16.04 Ubuntu release. Is there something that can be done about this? or any tips/advice that I may be missing here?

Thank you

**Comment by xuhdev** [comment]
In the first case, I don't know. Vim plugins are not supposed to freeze the system, in any case, no matter how it is written. I guess there's something else going on...

In the second case, I think you probably haven't successfully installed the plugin. How did you install it?

**Comment by RJ-Russell** [comment]
My fix was to go back to ubuntu 14.04 on my main machine, and everything works just fine. On my laptop I'm running Arch and there isn't any issues there.

I think it had something to do with Ubuntu 16.04? Not quite sure. Considering I won't be making the switch to 16.04 any time soon again, I won't be able to test it out again.

**Comment by xuhdev** [comment]
Yes, you can wait for Ubuntu to incorporate more bug fixes before switching.
