### ISSUE TITLE
does not work in insert mode

### ISSUE THREAD

**Issue by divinites** [xuhdev/vim-latex-live-preview#20]
Hi, this is a very helpful plug-in ,thanks for your outstanding work!

In my case, it does not work when Vim is in insert mode, I can type a whole paragraph and the pdf file will not refresh; however, if I changed to command mode, then every single step, the pdf file changes.  This is not a big problem, but it seems that in your demonstration, the live preview works even in insert mode.

I am using OSX el capitan, VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  5 2016 23:18:50)

with Skim and Preview (evince does not work for me, when I installed evince using homebrew).

**Comment by xuhdev** [comment]
What is your setting of `'updatetime'`?

**Comment by divinites** [comment]
I tried setting update time to 1, 10, 50, 200.  The results are all the same. When I typed ESC to exit the insert mode, the pdf instantly refreshed.

**Comment by divinites** [comment]
I noticed that there is a CursorHoldI event in the end of the plugin, so it should work in insert mode, I am quite curious about why it actually doesn't.
