### ISSUE TITLE
python/dyn instead of python

### ISSUE THREAD

**Issue by giper45** [xuhdev/vim-latex-live-preview#24]
Hello, in my default vim installed Mac Version there's the following python support: 
```
 +python/dyn
-python3 
``` 
It seems that there is dynamic python library support, but when I run with enabled plugin vim  error still happens:
```
vim-live-preview: Python initialization failed.
 ```
Is there any way to use dynamic python without compiling vim for the static python library ? Thanks in advance!

**Comment by xuhdev** [comment]
The plugin only calls `has('python')` to see whether python APIs are accessible. You can try the following and see the output:

     :echo has('python')

**Comment by giper45** [comment]
It gives 1...  but the error appears anyway...strange doesn't?

**Comment by ranguli** [comment]
@giper45 Was this ever resolved?

**Comment by giper45** [comment]
Hi @ranguli unfortunately I wasn't able to use latex preview with python/dyn , even by editing the plugin and by supporting the python/dyn library it didn't work. I don't know if it's a Mac problem, anyway a solution could be to download  vim source code and compile it by enabling the python support and by replacing the  native mac vim with the  compiled vim. I didn't try this, and I'm using   a mix of texshop (mac native latex editor) to update the pdf preview  with ctrl+R and mac native vim to edit latex files more quickly. If you try to compile vim let me now if the plugin works!

**Comment by ranguli** [comment]
@giper45 My solution (documented in issue #12 ) is the same as yours, I had to re-compile Vim with ```python3``` support in order to remove ```python/dyn``` and change the calls to ```python``` to ```python3``` in the code in order for it to work. Based on this I think it's safe to assume that there's no support ```python/dyn``` right now. I'll make a pull request on the README and add it as a known issue.

**Comment by badouralix** [comment]
Fun fact: here is my working config:

```bash
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun  8 2017 20:53:45)
Included patches: 1-628
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+python/dyn      +python3/dyn
```

**Comment by ranguli** [comment]
@badouralix Funky. So both of your Vim installations support ```+python/dyn```, the only differences in your environments being macOS vs Arch and consequently macOS's supplied version of Vim vs a compiled one. 

But if they both support ```+python/dyn```, that shouldn't matter.. right?
