### ISSUE TITLE
Faile to compile

### ISSUE THREAD

**Issue by muralikodali** [xuhdev/vim-latex-live-preview#29]
pdf viewer is zathura and os is ubuntu mate 16.04.
pdflatex and xelatex are installed. when i try to compile ,
if fails giving output - Failed to compile.

**Comment by badouralix** [comment]
Could you provide the command you use in your shell that compiles correctly your tex project, and the output of `:echo b:livepreview_buf_data` after running `:LLPStartPreview` in vim?

**Comment by muralikodali** [comment]
Following is the output of :echo b:livepreview_buf_data

{'root_dir': '/home/murali/Downloads/inbsbi', 'tmp_dir': '/tmp/vim-latex-live-preview-opaUeL', 'run_cmd': 'env TEXMFOUTPUT=/tmp/vim-latex-live-preview-opaUeL/
home/murali/Downloads/inbsbi TEXINPUTS=/tmp/vim-latex-live-preview-opaUeL/home/murali/Downloads/inbsbi:/home/murali/Downloads/inbsbi: pdflatex -shell-escape -
interaction=nonstopmode -output-directory=/tmp/vim-latex-live-preview-opaUeL/home/murali/Downloads/inbsbi /tmp/vim-latex-live-preview-opaUeL/home/murali/Downl
oads/inbsbi/tes.tex', 'tmp_src_file': '/tmp/vim-latex-live-preview-opaUeL/home/murali/Downloads/inbsbi/tes.tex'}

**Comment by badouralix** [comment]
What is the content of your `tes.tex` file? (using backtick quotes for better readability)

**Comment by muralikodali** [comment]
Two files tes.tex and suc.tex are attached. tes.tex is successfully compiled with xelatex in texstudio, where as in vim-latex-live-preview it is not happening. second file suc.tex  is successfully compiled with pdflatex in texstudio as well as in vim-latex-live-preview. It shows live-preview is not calling xelatex as compiling engine. OS is Ubuntu Mate 16.04

[texfiles.zip](https://github.com/xuhdev/vim-latex-live-preview/files/1109011/texfiles.zip)

**Comment by badouralix** [comment]
`pdflatex` is called as the binary is found and is used as a default engine. To override this behavior, you can add `let g:livepreview_engine = 'xelatex'` in your `vimrc` file.
Feel free to describe another default behavior that could be implemented to enhance `vim-latex-live-preview`.

Apart from that, I can't reproduce the bug on my machine, `tes.tex` is successfully compiled even with `pdflatex`. Maybe you can paste the output of compiling this file with `pdflatex` in TeXstudio to see what's going on...

**Comment by muralikodali** [comment]
compiling tes.tex with pdflatex got the error : ! pdfTeX error (font expansion): auto expansion is only possible with scalable fonts. I have added \usepackage{lmodern} to tex file, after googling the error and compiled with pdflatex successfully . Adding let g:livepreview_engine = 'xelatex' to .vimrc as suggested by you also worked well.

Thanks for your guidance
