### ISSUE TITLE
Doesn't work let g:livepreview_previewer

### ISSUE THREAD

**Issue by lazygreed** [xuhdev/vim-latex-live-preview#30]
i wrote let g:livepreview_previewer = 'mupdf'
but it doesn't start viewer
only run  evince or okular if they installed

**Comment by badouralix** [comment]
Could you provide info on your system, your `vimrc` and a tex file which fails opening `MuPDF`?

`MuPDF` actually shows up on my computer with this exact same config line `let g:livepreview_previewer = 'mupdf'`
Nonetheless, `mupdf` doesn't provide autoreload feature, which is pretty closed to #17. A basic workaround would be to press `r` within `mupdf` whenever you want to update the preview. A possible fix would be to send a `SIGHUP` to the viewer each time a compilation ends.

**Comment by lazygreed** [comment]
Lenovo g50-45, AMD A6-6310 (1.8 - 2.4 GHz) / RAM 4 GB / HDD 500 GB / AMD Radeon R5 M230, 1 GB
using archlinux, i3wm

here's vimrc
```Vim script
set number
set nowrap
set hlsearch
syntax on
imap qq <Esc>

set nocompatible
filetype off  

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

"github
Plugin 'VundleVim/Vundle.vim'
Plugin 'PotatoesMaster/i3-vim-syntax'
Plugin 'xuhdev/vim-latex-live-preview'
Plugin 'vim-scripts/Align'
"Plugin 'Lokaltog/vim-powerline'

"=========THEMES============
Plugin 'morhetz/gruvbox'

call vundle#end()
filetype plugin indent on

colorscheme gruvbox
set background=dark

autocmd Filetype tex setl updatetime=1
```

And tex file
```TeX
\documentclass[11pt]{article}

\usepackage[margin=1in, paperwidth=8.5in, paperheight=11in]{geometry}
\begin{document}

\title{Lol the \LaTeX \ test}
\author{}
\date{\today}
\maketitle

Some shit..
\begin{Huge}
        \textbf{ $$\frac{12}{A+B/3} = 12$$ }
\end{Huge}
\end{document}
```

**Comment by badouralix** [comment]
Where is the line `let g:livepreview_previewer = 'mupdf'` in `vimrc`?
Could you also provide the output of `:echo b:livepreview_buf_data` after running `:LLPStartPreview` in vim?

**Comment by lazygreed** [comment]
lol, it start work after adding line to `vimrc` .
Why it doesn't work if use it just in document before typing `:LLPStartPreview`

**Comment by badouralix** [comment]
This feature is in the roadmap 😉 
One of the main improvements I wanted to understand / to make before featuring this was the scoping of variables in the plugin. I'm a bit afraid that it would break some other behaviors otherwise...
