### ISSUE TITLE
probot-stale integration

### ISSUE THREAD

**Issue by badouralix** [xuhdev/vim-latex-live-preview#33]
@xuhdev: is it possible to install [probot-stale](https://github.com/probot/stale) in this repo?

It is a great tool to deal with old issues and pull requests. Also, the bot is configurable with a simple file hosted within the repo.

See [how-to](https://github.com/apps/probot-stale).

Thank you!

**Comment by xuhdev** [comment]
This has been installed now. Please lemme know if you have any questions!

**Comment by badouralix** [comment]
Thanks!
