### ISSUE TITLE
PDF output only updates on save

### ISSUE THREAD

**Issue by ranguli** [xuhdev/vim-latex-live-preview#36]
## Expected behavior

PDF updates after typing

## Actual behavior

PDF only updates after :w 

## Steps to reproduce

Tell us how it occurs

1. :LLPStartPreview on a LaTeX document
1. Try to edit document
1. Save in order to see changes

## System configuration

- **Vim version**:

``` bash
#VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 25 2017 13:17:56)
Included patches: 1-771
Compiled by ranguli@swoosh
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      -terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
+clientserver    +insert_expand   +packages        +title
+clipboard       +job             +path_extra      +toolbar
+cmdline_compl   +jumplist        +perl            +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       -python          +viminfo
+cscope          +lispindent      +python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +startuptime     +xpm
+eval            +mouse_dec       +statusline      +xsmp_interact
+ex_extra        -mouse_gpm       -sun_workshop    +xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -ldl  -L/usr/lib -llua5.1 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config -lpython3.5m  -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm  
```

- **Platform**:
Xubuntu 16.04

**Comment by badouralix** [comment]
Funny bug, specially because of [this line](https://github.com/xuhdev/vim-latex-live-preview/blob/45d6e21592e8aa4a998fb5604cf0d6d0ada5d08f/plugin/latexlivepreview.vim#L257) which is supposed to ensure the same behavior whether one stops writing or saves file.

Just to be sure: could it be a previewer issue ? That is the pdf is actually recompiled and up-to-date in the temp dir, but not shown

Or could it be related to your `python3`-patch ? About that, can you provide a [gist](https://gist.github.com/) of this patch that I can try ? ( you don't need to bother with versioning and pull requesting for now )

**Comment by ranguli** [comment]
AFAIK, Zathura was listed as a supported PDF reader, but I'll try it with another one. Which reader are you using? 

Here's a [gist](https://gist.github.com/ranguli/747afe7a2c39ab7e585bb8f258792d86) (no quality control, just straight copypaste) with the patch and I expanded the statement that checks for python into two separate ones in order to tell which one fails if a dependency is missing.

**Comment by badouralix** [comment]
Personally, I'm using [evince](https://www.archlinux.org/packages/extra/x86_64/evince/).

_Good point:_ your patch is working fine with my configuration `+python3/dyn` 👍 

_Problem:_ I can't reproduce your bug with [zathura](https://wiki.archlinux.org/index.php/Zathura) and [zathura-pdf-mupdf](https://www.archlinux.org/packages/community/x86_64/zathura-pdf-mupdf/). Which pdf backend are you using? Otherwise, could your provide an actual tex project which fails? (files, filenames and pathnames)

**Comment by ranguli** [comment]
Looks like evince also doesn't refresh for me until I save the document. What's the best way of telling what the PDF backend is? (Maybe we should add a debugging command that prints out things like PDF viewer, PDF backend, etc. Any tex document will fail, whether it's in the same root directory as where I ran vim or otherwise.

**Comment by badouralix** [comment]
I would say it depends on how you installed zathura.

Oh, I ran into this bug within a special case, and this is why there is [this known issue](https://github.com/xuhdev/vim-latex-live-preview/blob/2cad7426de4344428a45eba1192944c0bf9a35e6/README.md#project-tree). I never found out why... But we should dig then!

Yeah, we should definitely add a debugging command! And [ask for the output when an issue is opened](https://github.com/xuhdev/vim-latex-live-preview/blob/master/.github/ISSUE_TEMPLATE.md). Something like `:echo llp_debug` or `LLPDebug` or `LLPShowDebug` or `LLPOutputDebug` etc.
