### ISSUE TITLE
Latex LivePreview pdf file is not autoloading the pdf file

### ISSUE THREAD

**Issue by qaisern** [xuhdev/vim-latex-live-preview#42]
## Expected behavior

vim-latex-live-preview does not appear to be working properly

Tell us what should happen
Any edits that i am making in the latex file are not refreshing in the pdf file.

## My configuration is as follows
OS: Mac OSX El Captain version 10.11.6
Vim Version 

    ~  vim --version                                                                                 20:33:00 26/09/2017
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  2 2017 03:55:24)
MacOS X (unix) version
Included patches: 1-596
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc

PDF Viewer : evince GNOME Document Viewer 3.26.0

## Actual behavior

I can launch the PDFViewer evince with a command  :LLPStartPreview from vim..
But the pdf document is not refreshing when i make any changes to the doument ... i have to manualy select reload from evimce for the pdf document to reflect the changes to the document

**Comment by badouralix** [comment]
Hi @qaisern 
Thanks for reporting the issue! As manually reloading works, it seems to be a viewer issue rather than `vim-llp` related.

I didn't know `evince` was available on Mac OS X. Is it from MacPorts as describe in the [wiki](https://github.com/xuhdev/vim-latex-live-preview/wiki/Known-Working-PDF-Viewers)?
Have you tried using other pdf viewers, like Skim or Preview?

**Comment by qaisern** [comment]
I installed evince via homebrew... 

Preview works (when you move the cursor/focus on preview) .. but it does not live refresh/reload the document when changes are being made on the latex file..

I will try installing skim ...

**Comment by qaisern** [comment]
Hi @badouralix 
I tried it again with skim, it works like dream.
Thank you ...
