### ISSUE TITLE
LLPStartPreview does not open Preview and neither compile the tex file

### ISSUE THREAD

**Issue by plopezmp** [xuhdev/vim-latex-live-preview#44]
## Expected behavior

I have installed the plugin.

## Actual behavior

My Vim installation recognize the command

`:LLPStartPreview`

but it does nothing.
## Steps to reproduce
My .vimrc is the following:

```
set runtimepath+=~/.vim_runtime

 source ~/.vim_runtime/vimrcs/basic.vim
 source ~/.vim_runtime/vimrcs/filetypes.vim
 source ~/.vim_runtime/vimrcs/plugins_config.vim
 source ~/.vim_runtime/vimrcs/extended.vim

 try
 source ~/.vim_runtime/my_configs.vim
 catch
 endtry

 autocmd Filetype tex setl updatetime=1
 let g:livepreview_previewer = 'open -a Skim'
```

I have also tried 'Preview' Application of Mac OSX
I have MacTeX last version installed in my computer.

## System configuration

- **Vim version**:

```zsh
# output of `vim --version`
```

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
Included patches: 1-898, 8056
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
-- More --

installed with 'homebrew'.

The rest of plugins installed are by default the plugins of

[https://github.com/amix/vimrc](https://github.com/amix/vimrc)
- **Platform**:
Mac OSX Sierra (v 10.12.6)

**Comment by badouralix** [comment]
Hi @plopezmp! Is there any error message? Could you paste your tex file and the output of `:echo b:livepreview_buf_data` after attempting to run `:LLPStartPreview`?

**Comment by plopezmp** [comment]
Thank you to answer.
The file is the following:

`\documentclass{article}

\title{SenZors}
\author{Sustainable Computing Research}
\date{October 2014}
\maketitle

\begin{document}

\section{Introduction}

Real time communication platform for sensor devices

\subsection{What is SneZors}

Secured platform to share your sensor data

\subsection{Why SneZors}

Keep sharing your sensors

\section{Technologies}

\begin{enumerate}
\item Websockets 
\item Android
\item IOS
\end{enumerate}

\section{Downloads}

\hyperref{''https://play.google.com/store/apps/details?id=com.score.senzors&hl=en''}

\end{document}
`


and the output after LLStartPreview of `:echo b:livepreview_buf_data` is:

`{'root_dir': '/Users/plm/Desktop', 'py_exe': 'python', 'tmp_dir': '/var/folders/6f/4yxxrf_d6gq_0cxsjxvtqzn00000gn/T/vim-la
tex-live-preview-VdEz6h', 'run_cmd': 'env TEXMFOUTPUT=/var/folders/6f/4yxxrf_d6gq_0cxsjxvtqzn00000gn/T/vim-latex-live-prev
iew-VdEz6h/Users/plm/Desktop TEXINPUTS=/var/folders/6f/4yxxrf_d6gq_0cxsjxvtqzn00000gn/T/vim-latex-live-preview-VdEz6h/User
s/plm/Desktop:/Users/plm/Desktop: pdflatex -shell-escape -interaction=nonstopmode -output-directory=/var/folders/6f/4yxxrf
_d6gq_0cxsjxvtqzn00000gn/T/vim-latex-live-preview-VdEz6h/Users/plm/Desktop /var/folders/6f/4yxxrf_d6gq_0cxsjxvtqzn00000gn/
T/vim-latex-live-preview-VdEz6h/Users/plm/Desktop/kk.tex', 'tmp_src_file': '/var/folders/6f/4yxxrf_d6gq_0cxsjxvtqzn00000gn
/T/vim-latex-live-preview-VdEz6h/Users/plm/Desktop/kk.tex'}`

Best regards

**Comment by plopezmp** [comment]
There were no error messages.

**Comment by badouralix** [comment]
There are a couple of mistakes in the tex file (busted while running `pdflatex <filename>` by hand):
- `hyperref` package must be loaded in the preamble
- `\maketitle` must be called after `\begin{document}`
- use `\url` instead of `\hyperref` with an url

```latex
\documentclass{article}

\usepackage{hyperref}

\title{SenZors}
\author{Sustainable Computing Research}
\date{October 2014}

\begin{document}

  \maketitle

  \section{Introduction}

    Real time communication platform for sensor devices

    \subsection{What is SneZors}

      Secured platform to share your sensor data

    \subsection{Why SneZors}

      Keep sharing your sensors

  \section{Technologies}

    \begin{enumerate}
      \item Websockets
      \item Android
      \item IOS
    \end{enumerate}

  \section{Downloads}

    \url{https://play.google.com/store/apps/details?id=com.score.senzors&hl=en}

\end{document}
```

`vim-llp` should work correctly after these changes 😉

**Comment by plopezmp** [comment]
Ok, Thank you. If Skim o Preview are opened the command LLPStartPreview shows the PDF. I would ask you how Ia can make the previewed file to update after any modification/edition of the tex file?

**Comment by badouralix** [comment]
The previewed file should update automatically. Actually, it depends on the previewer you are using. The feature is known to be working with some of them: https://github.com/xuhdev/vim-latex-live-preview/wiki/Known-Working-PDF-Viewers.

**Comment by qaisern** [comment]
I have the same issue .. I have loaded the plugin ... it worked before but for some apparent reason the pdf preview does not seem to load up
