### ISSUE TITLE
Foward search in the preview? 

### ISSUE THREAD

**Issue by angelleng** [xuhdev/vim-latex-live-preview#45]
Is there a way to enable forward/backward search in the preview pdf file? 
I am trying to use vim-latex-live-preview with skim.

**Comment by badouralix** [comment]
Hi @angelleng! What do you mean by "forward/backward search"? Like synctex support? If so, it reminds me #16, maybe you can try with `let g:livepreview_previewer = 'pdflatex -synctex=1'` in your `vimrc` dotfile.
