### ISSUE TITLE
Using Multirow Package Leads to Failed to Compile

### ISSUE THREAD

**Issue by Ripsta128** [xuhdev/vim-latex-live-preview#47]
## Expected behavior

LLP to compile my .tex file.

## Actual behavior

Running :LLPStartPreview outputs "failed to compile"

## Steps to reproduce

My document that's currently 300+ lines with other packages installed compiles just fine, as should as I add the line:
\usepackage{multirow}
throws error "failed to compile"

## System configuration

- **Vim version**:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  5 2017 23:26:48)
Included patches: 1-1272
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl/dyn
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminal
++builtin_terms  +fork()          +multi_lang      +terminfo
+byte_offset     +gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
-clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        +perl/dyn        +user_commands
+cmdline_hist    +keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xpm
+eval            +mouse_dec       +statusline      -xsmp
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm     

```
Arch Linux "4.9.56-1-LTS"

**Comment by badouralix** [comment]
Hi @Ripsta128 

Thanks for reporting. I tried [this example](https://tex.stackexchange.com/a/73285) on the exact same system as you, and compilation through LLP succeeded. Thus the error doesn't seem related to `multirow`. My bet is there is a syntax error in the tex file. Could you try to compile it by hand in a shell?

**Comment by Ripsta128** [comment]
@badouralix I created a new .tex file then copy & paste that exact example since it compiled for you, but for me the error "failed to compile" continues to show. Now I'm able to compile the .tex file using the "latex" command and turn it into a .dvi file from which evince can read and the functions of multirow does indeed appear and work. My only issue is I would have to do it manually every time I want to visually see my file to correct for errors.

**Comment by xuhdev** [comment]
@Ripsta128 I can't reproduce either. Can you ensure your working directory is clean and try again?

**Comment by Ripsta128** [comment]
@xuhdev Sorry I'm still pretty new to the whole Latex scene, but what do you mean by clean directory? My .tex file is located in "~/Documents/SomeFolder/file.tex"

**Comment by xuhdev** [comment]
Just to clean all other files. How about creating a new empty directory and copy `file.tex` in?

**Comment by Ripsta128** [comment]
@xuhdev Damn, that solved the problem. Any reason while it wouldn't compile if it's in a folder with files in it including but not limited to .tex?

**Comment by xuhdev** [comment]
@Ripsta128 LaTeX or LaTeXmk sometimes cache things.
