### ISSUE TITLE
Can't understand how to set location properly

### ISSUE THREAD

**Issue by fedemengo** [xuhdev/vim-latex-live-preview#51]
On macOS I'm currently having trouble in making the PDF to be saved in the same folder of the *.tex file.

I tried to set the absolute path of the root file (I assumed the root file is the *.tex file??) but the PDF is stored in some folders located at `/private/var/folders/zd/zqy4ndl16tg8zhttq7k0gn5m0000gn/T/vim-latex-live-preview-ZoEibD/Users/fedemengo/Projects/_docs/Vim/Vim.pdf`

Where the path `/Users/fedemengo/Projects/_docs/Vim/` is where the .tex file is located.

**Comment by badouralix** [comment]
Hi @fedemengo! Actually, what you're looking for is **not** what this plugin is intended to be. The plugin only provides a preview of the current buffer (which may be different from the actual currently saved file), and having a temporary PDF file in some temporary folder is only a trick we use to achieve outputting the preview. Whereas generating the *prod-ready* PDF should be done independently from vim-llp, namely compiling it with a command line tool or another vim plugin.

**Comment by fedemengo** [comment]
Ok got it, so I guess there is no way to make the PDF to be saved in a specific directory?

**Comment by badouralix** [comment]
Indeed.
