### ISSUE TITLE
:LLPStartPreview runs with no errors, fails to compile or open pdf viewer

### ISSUE THREAD

**Issue by kappanose** [xuhdev/vim-latex-live-preview#57]
## Expected behavior

Preview Starts

## Actual behavior

Preview does not compile or open an editor (I ran the start preview command and checked manually)

Neovim v0.2.2
The plugin installs with no errors, and no errors appear after running :LLPStartPreview in neovim.  I also manually compiled the tex file with pdflatex from the command line, which worked.  This was working earlier today, and I don't recall changing anything.  My vim init file contains:

syntax on

call plug#begin('~/.vim/plugged')

Plug 'artur-shaik/vim-javacomplete2'
Plug 'xuhdev/vim-latex-live-preview', {'for': 'tex'}
Plug 'Shougo/deoplete.nvim', {'do': 'UpdateRemotePlugins'}
Plug 'sbdchd/neoformat'
Plug 'dylanaraps/wal.vim'
" Plug 'lervag/vimtex', { 'for': 'tex'}

call plug#end()

colorscheme wal
let g:deoplete#enable_at_startup=1
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.java = '[^. *\t]\.\w*'
let g:deoplete#sources = {}
let g:deoplete#sources._ = []
let g:deoplete#file#enable_buffer_path = 1

highlight Pmenu ctermbg=8 guibg=2
highlight PmenuSel ctermbg=1 guifg=2 guibg=2
highlight PmenuSbar ctermbg=0 guibg=2

augroup astyle
"       autocmd!
        autocmd BufWritePre * Neoformat
augroup END

autocmd Filetype java set number

autocmd Filetype tex let g:livepreview_engine='pdflatex'put of 
autocmd Filetype tex let g:livepreview_previewer='zathura'
autocmd Filetype tex set syntax=context
autocmd Filetype tex setl updatetime=1000

Thanks in advance.

Edit:
Here is output of :echo b:livepreview_buf_data after attempting to open preview
{'root_dir': '/home/kappanose/Documents/math/', 'py_exe': 'python3', 'tmp_dir': '/tmp/vim-latex-live-preview-dxir9mhu', 'run_cm
d': 'env TEXMFOUTPUT=/tmp/vim-latex-live-preview-dxir9mhu/home/kappanose/Documents/math/ TEXINPUTS=/tmp/vim-latex-live-preview-
dxir9mhu/home/kappanose/Documents/math/:/home/kappanose/Documents/math/: pdflatex -shell-escape -interaction=nonstopmode
-output-directory=/tmp/vim-latex-live-preview-dxir9mhu/home/kappanose/Documents/math/promys /tmp/vim-latex-live-preview-dxir9mhu/home
/kappanose/Documents/math/app', 'preview_running': 1, 'tmp_src_file': '/tmp/vim-latex-live-preview-dxir9mhu/home/kappanose/Doc
uments/math/app'}

So 'preview_running': 1 suggests that the preview should have opened, yet it does not even compile.

**Comment by kappanose** [comment]
Okay, so commenting out the 

if v:version < 700                                                              
    finish                                                                     
endif

lines in .vim/plugged/vim-latex-live-preview/plugin/latexlivepreview.vim works.  I think this is because I'm using neovim instead of vim.  For now, I have this commented out, but would appreciate it if the developers added neovim version support (so when I update the plugin I don't have to manually comment out the lines every time).  Preview works flawlessly now.

**Comment by xuhdev** [comment]
I just tested it on neovim. `v:version` on neovim seems to be larger than 700. Are you sure this is the reason that it does not work?

**Comment by ZaheenAzad** [comment]
Hi, I am having the almost same Issue under exact same setup.
Neovim v0.2.2
The plugin installs without any error.
but when I run ":LLPStartPreview"  --> "Failed to compile" appears.
But I have comiled the same file in other ways, which compiles perfectly.

**Comment by tourdetour** [comment]
Same issue here, I have the following file 
`\empty Hello world!\bye`
Which compiles fine using pdftex, and with vim-latex-live-preview, ":LLPStartPreview" leads to "Failed to compile" with no further error.

**Comment by redapemusic35** [comment]
I am having the same issue with macvim. the document compiles properly every other way except with :LLPStartPreview.

**Comment by byteofsoren** [comment]
I to have the same problem.

**Comment by redapemusic35** [comment]
I was able to fix mine. However I am not sure exactly how. I will try to figure it out and let you know.

**Comment by Migacz85** [comment]
Yesterday I had working it perfectly but today:
 ":LLPStartPreview" 
is producing exactly the same problem like in this therad :/ What the heck?

**Comment by ciolansteen** [comment]
Same behaviour. But only when the file is in the root of user's home directory or lower (/home/. or /home/user/.). Any higher level works fine. Anyway, LLPStartPreview creates the /tmp/vim-latex-live-preview-xxxxxxxx/whatever.pdf file but cannot open it. 

Vim

**Comment by Migacz85** [comment]
@ciolansteen Check if you can manually compile latex to pdf without errors. I found that if there were errors while compiling - and this could be easyly resovled by passing few enters - this plugin had problems after to render pdf. And did not produce any information about that to the user.

**Comment by ciolansteen** [comment]
already checked and yes, i can. Another wierd thing would be, besides /home/. and /home/user/. there's also /home/user/.local and /home/user/.local/share, all other levels work fine as well as any other directory created in .local
I manually compiled on all these locations and everything worked correctly.

**Comment by xuhdev** [comment]
Can any of you test whether removing line 19-21 in `latexlivepreview.vim` resolves the issue? The three lines read:

```vim
if v:version < 700
    finish
endif
```

**Comment by SevenTailCat** [comment]
hi~I have removed the three lines in `latexlivepreview.vim`, but it does not work. how can i do now?

**Comment by xuhdev** [comment]
@SevenTailCat Are you on neovim?

**Comment by SevenTailCat** [comment]
No,I am on macvim which was installed by homebrew.

**Comment by xuhdev** [comment]
It looks like there are many different types of "not working" in this thread. I'll close this issue. Please open a new issue and state what kind of error you are encounting -- we'll start from there.

**Comment by SevenTailCat** [comment]
> It looks like there are many different types of "not working" in this thread. I'll close this issue. Please open a new issue and state what kind of error you are encounting -- we'll start from there.

OK，Thanks.

**Comment by tobinzt** [comment]
> > It looks like there are many different types of "not working" in this thread. I'll close this issue. Please open a new issue and state what kind of error you are encounting -- we'll start from there.
> 
> OK，Thanks.

Did resolve the issue?

**Comment by fadli0029** [comment]
You probably have done this, but just in case, make sure you actually have `texlive` installed:
`sudo apt install texlive-full`
