### ISSUE TITLE
won't compile main file from sub files.

### ISSUE THREAD

**Issue by notaduck** [xuhdev/vim-latex-live-preview#60]
## Expected behavior
Let's say I've two files, main.tex second.tex and `% !TEX root = <main.tex>` is placed in top of the secon.tex, then the document should be compled from main.tex
## Actual behavior
Nothing happends at all. only if I save and compiles the doc from main.tex
Tell us what happends.

## System configuration

- **Vim version**: 

```bash
NVIM v0.2.2

```

- **Platform**:
```
Manjaro
```

**Comment by ChrisLane** [comment]
The plugin currently doesn't follow the documentation and will only match a comment with lowercase "tex", I've submitted a pull request to change that though.

Also, you shouldn't be including the <>, just the filename

**Comment by notaduck** [comment]
Thanks @ChrisLane ! It seems that `TEX` was causing the error, and ofcourse `< >` was a mistake ;)  
Now I just need to figure out why I've to save the document before the preview updates. there isn't that must live over it now.
