### ISSUE TITLE
Missing error log 

### ISSUE THREAD

**Issue by notaduck** [xuhdev/vim-latex-live-preview#63]
## Expected behavior
When a file fails to compile, then I was hoping there was an error log or something which would indicate what the error was/is
Tell us what should happen

## Actual behavior

I only see a message which tells me that it "failed to compil"

## Steps to reproduce
make a syntax error and start vim-latex-live-preview

**Comment by jarvie-mei** [comment]
I think so

**Comment by Migacz85** [comment]
So where are the error logs ?

**Comment by notaduck** [comment]
@Migacz85 I still don't think there is any, I've moved to vim-tex.

**Comment by Migacz85** [comment]
Yes, I was reading plugin code yesterday there is only a function to display error when there is shell error. I don't know what happend. But at the end of the day this plugin started working again. But if something like that is happening probably sooner or later I will face this bug again. It would be great to have some kind of a log. This plugin when works - is excelent -. But there has to be more control over errors, without information what goes wrong is impossible to debug that.
