### ISSUE TITLE
Faile to compile on OS X

### ISSUE THREAD

**Issue by N214** [xuhdev/vim-latex-live-preview#66]
Hello, 

i'm try to use the vim-preview with the build-in Preview on OS X but it if fails giving output - Failed to compile.

my vimrc:
`let g:livepreview_previewer = 'open -a Preview'`

:echo b:livepreview_buf_data after getting failed to compile:
`echo b:livepreview_buf_data {'root_dir': '/Users/MacBook/latextest', 'py_exe': 'python', 'tmp_dir': '/var/folders/jc/7wv525k1279ghfbp4knf75z40000gn/T/vim-latex-live-preview-HK1rJ6', 'run_cmd': '
env TEXMFOUTPUT=/var/folders/jc/7wv525k1279ghfbp4knf75z40000gn/T/vim-latex-live-preview-HK1rJ6/Users/MacBook/latextest TEXINPUTS=/var/folders/jc/7wv525k1279ghfbp4knf7
5z40000gn/T/vim-latex-live-preview-HK1rJ6/Users/MacBook/latextest:/Users/MacBook/latextest: pdflatex -shell-escape -interaction=nonstopmode -output-directory=/var/fol
ders/jc/7wv525k1279ghfbp4knf75z40000gn/T/vim-latex-live-preview-HK1rJ6/Users/MacBook/latextest /var/folders/jc/7wv525k1279ghfbp4knf75z40000gn/T/vim-latex-live-preview
-HK1rJ6/Users/MacBook/latextest/test', 'tmp_src_file': '/var/folders/jc/7wv525k1279ghfbp4knf75z40000gn/T/vim-latex-live-preview-HK1rJ6/Users/MacBook/latextest/test'}`

**Comment by xuhdev** [comment]
Does the compilation works on the command line? What is the error of the output?

**Comment by N214** [comment]
Pdflatex tex file works. Command LLPStartPreview gives me Faile to compile
