### ISSUE TITLE
problem with latexmk

### ISSUE THREAD

**Issue by TillLindemann** [xuhdev/vim-latex-live-preview#67]
First of all,everythings works fine when I am writing docs in English.But I got problems when I compile with Chinese.The actual command that I use in terminal to compile the tex file is :"latexmk -xelatex file.tex",and it worked.But when I set in .vimrc :"let g:livepreview_engine='latexmk'.'-xelatex'"，it shows fail to compile.I am not familar with latex,only follow the compiling instructions,can you give me a solution about this?

**Comment by xuhdev** [comment]
Thanks! Good to know you fixed it.
