### ISSUE TITLE
Error detected while processing function <SNR>9_StartPreview: line   68: E121: Undefined variable: s:engine E15: Invalid expression: 'env ' .       'TEXMFOUTPUT=' . l:tmp_root_dir . ' ' .       'TEXINPUTS=' . l:tmp_root_dir                    . ':' . b:livepr eview_buf_data['root_dir']                    . ': ' . s:engine . ' ' .       '-shell-escape ' .       '-interaction=nonstopmode ' .       '-output-dir ectory=' . l:tmp_root_dir . ' ' .       l:root_file line   81: E716: Key not present in Dictionary: run_cmd E116: Invalid arguments for function system

### ISSUE THREAD

**Issue by DavisGuohua-xie** [xuhdev/vim-latex-live-preview#68]
## Expected behavior

Tell us what should happen
   The systme/ mac should launch Preview and covert the currrent latex file into pdf file
## Actual behavior

Tell us what happens instead

Error detected while processing function <SNR>9_StartPreview:
line   68:
E121: Undefined variable: s:engine
E15: Invalid expression: 'env ' .       'TEXMFOUTPUT=' . l:tmp_root_dir . ' ' .       'TEXINPUTS=' . l:tmp_root_dir                    . ':' . b:livepr
eview_buf_data['root_dir']                    . ': ' . s:engine . ' ' .       '-shell-escape ' .       '-interaction=nonstopmode ' .       '-output-dir
ectory=' . l:tmp_root_dir . ' ' .       l:root_file
line   81:
E716: Key not present in Dictionary: run_cmd
E116: Invalid arguments for function system

## Steps to reproduce
I am thinking it may be my setup issue since this is my first time attempt using it to complete my hw,
pushed in a github repo as well [https://github.com/DavisGuohua-xie/HW5]().

My .vimrc config 

 1 set nocompatible              " be iMproved, required
  2 filetype off                  " required
  3
  4 " set the runtime path to include Vundle and initialize
  5 set rtp+=~/.vim/bundle/Vundle.vim
  6 call vundle#begin()
  7 " alternatively, pass a path where Vundle should install plugins
  8 "call vundle#begin('~/some/path/here')
  9
 10 " let Vundle manage Vundle, required
 11 Plugin 'VundleVim/Vundle.vim'
 12
 13 " A Vim Plugin for Lively Previewing LaTeX PDF Outputso ~/.vimrc
 14 Plugin 'xuhdev/vim-latex-live-preview'
 15 " All of your Plugins must be added before the following line
 16 call vundle#end()            " required
 17 filetype plugin indent on    " required
 18 " To ignore plugin indent changes, instead use:
 19 "filetype plugin on
 20 "
 21 " Brief help
 22 " :PluginList       - lists configured plugins
 23 " :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
 24 " :PluginSearch foo - searches for foo; append `!` to refresh local cache
 25 " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
 26 "
 27 " see :h vundle for more details or wiki for FAQ
 28 " Put your non-Plugin stuff after this line
 29
 30
 31
 32
 33
 34 :set nu
 35 autocmd Filetype tex setl updatetime=1
 36 let g:livepreview_previewer = 'open -a Preview'

Tell us how it occurs

1. follow this instruction ([https://coderwall.com/p/s1i5pw/latex-with-vim]())
1. install plugin 
1. : LLPStartPreview

## System configuration

- **Vim version**:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)
Garbage after option argument: "-version"
More info with: "vim -h"

```bash
# output of `vim --version`
```

- **Platform**:
mac

**Comment by barra51** [comment]
Hi Davis,

Can you resolve this problem? I have the same issue with the same environment.

Regards,

**Comment by badouralix** [comment]
Hi @DavisGuohua-xie @barra51, thanks for reaching out!

Do you have any of `pdflatex` or `xelatex` installed? Otherwise, which tool are you using to compile your tex code?

**Comment by hugoweslien** [comment]
Same problem here, using windows 10 with linux subsystem.

**Comment by DavisGuohua-xie** [comment]
@badouralix  
which pdflatex
/Library/TeX/texbin/pdflatex

**Comment by DavisGuohua-xie** [comment]
@barra51  no, i haven't
