### ISSUE TITLE
Swap warning

### ISSUE THREAD

**Issue by tomaszwojcik** [xuhdev/vim-latex-live-preview#7]
Hello

I use MacTeX and Mac OS X Preview as my preview program.
When I start the `:LLPStartPreview` and save the file I get the following error:

```
"latex-test.tex" 10L, 207C written
Error detected while processing function <SNR>60_Compile:
line   10:
E768: Swap file exists: /Users/twojcik/.vim_tmp/latex-test.tex.swp (:silent! overrides)
```

I don't want to disable the swap.

**Comment by harius** [comment]
Just add double slashes to paths in your config to avoid name collision:
```
set backupdir=~/.vim_bck//
set directory=~/.vim_tmp//
```

**Comment by nhooyr** [comment]
harius's solution worked great for me.

**Comment by satvug** [comment]
Your solution worked for me too, harius - thanks!

**Comment by badouralix** [comment]
As the name of the file written in the tmp dir is essential to make the plugin work on a multi files project, the only lasting solution is to use @harius trick. I'm closing this issue after referencing it in [the project readme](https://github.com/xuhdev/vim-latex-live-preview/blob/master/README.md). Feel free to re-open it whether something related happens.
