### ISSUE TITLE
Failed to compile neovim

### ISSUE THREAD

**Issue by gvgame** [xuhdev/vim-latex-live-preview#73]
First off, let me preface that this is an awesome plugin, I use it on my arch setup and it works like a charm. Having trouble on OSX though.

Neovim installs latex live preview with no issue. 
Keep getting a `failed to compile` error. Works fine from the command line, with `xelatex` but not from neovim. I read that warnings could cause errors so I fixed all the warnings and still got `failed to compile`. So, I tried doing a very simple document to see if it was `xelatex` that was the problem. When I did that it did not say failed to compile, but I got the following:
`nvim(81771,0x7fff986e2380) malloc: *** error for object 0x7ff005828800: incorrect checksum for freed object - object was probably modified after being freed.
  *** set a breakpoint in malloc_error_break to debug`
Here is the file I was trying 

```tex
\documentclass{article}

\begin{document}

\title{Introduction to \LaTeX{}}
\author{Author's Name}

\maketitle

\begin{abstract}
The abstract text goes here.
\end{abstract}

\section{Introduction}
Here is the text of your introduction.

\section{Conclusion}
Write your conclusion here.

\end{document}
```

- **Vim version**:
Running Neovim v0.3.1

- **Platform**: Mac OSX High Sierra 10.13.5

**Comment by xuhdev** [comment]
The malloc issue should be a neovim's issue, since plugins have no direct access to neovim's memory space -- if something is wrong there, it has to be an issue in neovim. Are you using an up-to-date neovim?

**Comment by gvgame** [comment]
Ya Neovim 0.3.1 is the latest version of neovim

**Comment by xuhdev** [comment]
I think the way to deal with this is try to produce some debug info and report them to neovim...
