### ISSUE TITLE
Evince does not reload automatically

### ISSUE THREAD

**Issue by zhuosongz** [xuhdev/vim-latex-live-preview#75]
Hi, I got a problem that the evince viewer does not reload automatically, and I have to reload it manually. Could you please help me with this? Thanks!

Also, after I set `let g:livepreview_previewer = 'open -a Skim'` as recommended, it also open the pdf file using Evince. How to set the previewer as `Skim`? Thanks!

**Comment by badouralix** [comment]
Hi @zhuosongz, thanks for reaching out
Did you added this command in your `.vimrc` or did you run it inside vim once the file was loaded?

**Comment by zhuosongz** [comment]
Thank you @badouralix . I added the command in my vimrc and it didn't work. And then I run it inside vim, and it still didn't work. Thanks!

**Comment by badouralix** [comment]
Would you mind pasting the output of `:echo b:livepreview_buf_data` after running `:LLPStartPreview`?
