### ISSUE TITLE
Failed to compile On Mac(Version 10.14 (18A391))

### ISSUE THREAD

**Issue by DavisGuohua-xie** [xuhdev/vim-latex-live-preview#76]
## Expected behavior
Open Preview.app and view the pdf file

## Actual behavior
Failed to compile
## Steps to reproduce
open a tex file with vim 
:LLPStartPreview
Failed to compile

Tell us how it occurs

1. vim  tex file
2.  : LLPStartPreview
3.  Failed to compile

## System configuration

- **Vim version**:

vim -version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 11 2018 20:21:01)
Garbage after option argument: "-version"
More info with: "vim -h"

```bash
bash_profile
  1 
  2 # added by Anaconda3 installer
  3 #export PATH="/Users/davis/anaconda3/bin:$PATH"
  4 export PATH="/usr/local/opt/qt/bin:$PATH"
  5 
  6 export PYTHONPATH="/usr/local/Cellar/python/3.7.0/bin/python3:$PYTHONPATH"
  7 
  8 export ANDROID_HOME="/Users/davis/Library/Android/sdk"
  9 
 10 export PATH=$ANDROID_HOME/platform-tools:$PATH
 11 
 12 export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
 13 
 14 export JAVA_HOME=/Library/Java/Home
 15 
 16 export PATH=$JAVA_HOME/bin:$PATH
 17 
 18 export PATH=”/Users/User_name/Desktop/apache-maven-3.5.4/bin”:$PATH
 19 
 20 export PATH=$PATH:/opt/gradle/gradle-4.10.2/bin
 21 
 22 # autojump
 23 
 24 [[ -s /Users/davis/.autojump/etc/profile.d/autojump.sh ]] && source /Users/davis/.autojump/etc/profile.d/autojump.sh






# output of `vim --version`
```
 vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 11 2018 20:21:01)
macOS version
Included patches: 1-450
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           +python            +viminfo
+conceal           +linebreak         -python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               +ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python@2/Frameworks -framework Python   -lruby.2.5.1 -lobjc 

- **Platform**:

Mac(Version 10.14 (18A391))

*~/.vimrc*

  1 
  2 "Plugins managed by Vundle
  3 
  4 set nocompatible
  5 filetype off
  6 
  7 set rtp+=~/.vim/bundle/Vundle.vim
  8 call vundle#begin()
  9 Plugin 'VundleVim/Vundle.vim'
 10 
 11 "LaTeX Plugins
 12 "Uncomment the following after installation of latex-suite
 13 Plugin 'xuhdev/vim-latex-live-preview'
 14 Plugin 'vim-latex/vim-latex'
 15 
 16 call vundle#end()
 17 filetype plugin indent on
 18 
 19 "LaTeX-Suite-aka-Vim-LaTeX Configuration
 20 let g:tex_flavor='latex' "Use vim-latex even when *.tex file is newcreated)
 21 autocmd BufEnter *.tex set sw=2
 22 
 23 let g:livepreview_previewer = 'open -a Preview'
 24 
 25 let g:livepreview_cursorhold_recompile = 0
 26 
 27 
 28 "set number line
 29 set nu

**Comment by xuhdev** [comment]
What kind of error message did you get?

**Comment by DavisGuohua-xie** [comment]
:echo g:loaded_vim_live_preview
1
:LLPStartPreview
Failed to compile

**Comment by DavisGuohua-xie** [comment]
> What kind of error message did you get?
\documentclass{article}
\usepackage{amsthm, amssymb, amsmath,verbatim}
\usepackage[margin=1in]{geometry}
\usepackage{enumerate}

\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\F}{\mathbb{F}}
\newcommand{\N}{\mathbb{N}}



\newtheorem*{claim}{Claim}
\newtheorem{ques}{Question}


\title{CSE 101 Homework 3}
\date{Fall 2018}

\begin{document}

\maketitle

This homework is due on gradescope Friday November 2nd at 11:59pm. Remember to justify your work even if the problem does not explicitly say so. Writing your solutions in \LaTeX is recommend though not required.

\begin{ques}[Verifying Shortest Path Lengths, 30 points]
Let $G$ be a directed, weighted graph with potentially negative edge weights, but no negative weight cycles. Let $s$ be a vertex of $G$. Using Bellman-Ford to compute the shortest path lengths from $s$ to the other vertices is somewhat slow, however verifying that the answer you have is correct is somewhat faster. Provide an algorithm that given values $d(v)$ for each vertex $v\in V$, determines whether or not $d(v)$ is the length of the shortest path from $s$ to $v$ for all $v$ (your algorithm should return a single TRUE/FALSE value, returning FALSE if there is \emph{any} vertex $v$ so that $d(v)$ is not the correct shortest path length from $s$). For full credit your algorithm should run in linear time or better.
\end{ques}

\begin{ques}[The Skyline Problem, 30 points]
A city's skyline is traced out by $n$ rectangular buildings. In particular, each building has a height $h_i$ and a base given by an interval $[x_i,y_i]$. For our purposes we will assume that the $x_i$ and $y_i$ used by the $n$ buildings are exactly the integers from $1$ to $2n$ without any repeats. The height of the skyline at location $\ell_i$ at a position $i$ is given by $\max_{i:x_i\leq \ell \leq y_i} h_i$. Give an algorithm to compute $\ell_1,\ell_2,\ldots,\ell_{2n}$. For full credit, your algorithm should run in time $O(n\log(n))$ or better. Hint: use divide an conquer. Your subproblems may need to look slightly more complicated than your original problem.
\end{ques}

\begin{ques}[Densest Interval, 30 points]
Given a set $S$ of $n$ real numbers and a positive real number $L$, give an algorithm to compute an interval of length at most $L$ that contains as many elements of $S$ as possible. For full credit, your algorithm should run in time $O(n\log(n))$ or better.
\end{ques}

\begin{ques}[Divide an Conquer Runtimes, 10 points]
For each of the following, give the asymptotic runtime of the following divide and conquer algorithms:
\begin{enumerate}[(a)]
\item An algorithm that splits a problem of size $n$ into five problems of size $n/3$ and does $O(n^{3/2})$ work combining the answers.
\item An algorithm that splits a problem of size $n$ into eight problems of size $n/2$ and does $O(n^3)$ work combining the answers.
\item An algorithm that splits a problem of size $n$ into three problems of size $2n/3$ and does $O(n^3)$ work combining the answers.
\item An algorithm that splits a problem of size $n$ into one problem of size $99n/100$ and does $O(1)$ work combining the answers.
\item An algorithm that splits a problem of size $n$ into two problems of size $2n$ and does $O(n)$ work combining the answers.
\end{enumerate}
\end{ques}


\begin{ques}[Extra credit, 1 point]
Approximately how much time did you spend on this homework?
\end{ques}

\end{document}

**Comment by DavisGuohua-xie** [comment]
> What kind of error message did you get?

Are we suppose to a pdf file open by preview ?
:echo g:loaded_vim_live_preview
1
:LLPStartPreview
Failed to compile

**Comment by xuhdev** [comment]
Did you try to compile on the command line? What is the return value of the latex compiler?

**Comment by jpchen** [comment]
same issue. company made me upgrade to mojave and it broke :(
compiles successfully via pdflatex on command line, but upon launch of the latex in vim, it says `vim-live-preview: Python initialization failed.`
then when running LLPStartPreview, i get
```
<details>
  <summary>expand</summary>
Error detected while processing function <SNR>25_StartPreview:
line    9:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
NameError: name 'tempfile' is not defined
line   11:
E716: Key not present in Dictionary: tmp_dir
E15: Invalid expression: b:livepreview_buf_data['tmp_dir'] . expand('%:p:r')
line   27:
E716: Key not present in Dictionary: tmp_src_file
E15: Invalid expression: b:livepreview_buf_data['tmp_src_file']
line   32:
E716: Key not present in Dictionary: tmp_src_file
E116: Invalid arguments for function fnamemodify(b:livepreview_buf_data['tmp_src_file'], ':p:h')
E15: Invalid expression: fnamemodify(b:livepreview_buf_data['tmp_src_file'], ':p:h')
line   33:
E121: Undefined variable: l:tmp_src_dir
E116: Invalid arguments for function isdirectory(l:tmp_src_dir))
E15: Invalid expression: (!isdirectory(l:tmp_src_dir))
line   38:
E121: Undefined variable: l:root_file
E15: Invalid expression: (l:root_file == b:livepreview_buf_data['tmp_src_file'])                          " if root file is the current file
line   48:
E121: Undefined variable: l:root_file
E116: Invalid arguments for function fnameescape(l:root_file)
E15: Invalid expression: fnameescape(l:root_file)
line   49:
E121: Undefined variable: l:tmp_root_dir
E116: Invalid arguments for function fnameescape(l:tmp_root_dir)
E15: Invalid expression: fnameescape(l:tmp_root_dir)
line   50:
E716: Key not present in Dictionary: tmp_dir
E116: Invalid arguments for function fnameescape(b:livepreview_buf_data['tmp_dir'])
E15: Invalid expression: fnameescape(b:livepreview_buf_data['tmp_dir'])
line   51:
E716: Key not present in Dictionary: tmp_src_file
E116: Invalid arguments for function fnameescape(b:livepreview_buf_data['tmp_src_file'])
E15: Invalid expression: fnameescape(b:livepreview_buf_data['tmp_src_file'])
line   55:
E121: Undefined variable: l:root_file
E15: Invalid expression: (l:root_file == b:livepreview_buf_data['tmp_src_file'])                          " if root file is the current file
line   60:
E716: Key not present in Dictionary: root_dir
E15: Invalid expression: 'lcd ' . b:livepreview_buf_data['root_dir']
line   63:
E716: Key not present in Dictionary: tmp_src_file
E15: Invalid expression: 'write! ' . b:livepreview_buf_data['tmp_src_file']
line   65:
E121: Undefined variable: l:tmp_root_dir
E15: Invalid expression: l:tmp_root_dir . '/' . fnamemodify(l:root_file, ':t:r') . '.pdf'
line   68:
E121: Undefined variable: l:tmp_root_dir
E15: Invalid expression: 'env ' .       'TEXMFOUTPUT=' . l:tmp_root_dir . ' ' .       'TEXINPUTS=' . l:tmp_root_dir                    . ':' . b:livepreview_buf_data['root_dir']                    . ': ' . s:engine . ' ' .       '-shell-escape ' .       '-interaction=nonstopmode ' .       '-output-directory=' . l:tmp_root_dir . ' ' .       l:root_file
line   81:
E716: Key not present in Dictionary: run_cmd
E116: Invalid arguments for function system
line   89:
E716: Key not present in Dictionary: root_dir
E116: Invalid arguments for function glob(b:livepreview_buf_data['root_dir'] . '/**/*.bib'))     " TODO: fails if unused bibfiles
E116: Invalid arguments for function split(glob(b:livepreview_buf_data['root_dir'] . '/**/*.bib'))     " TODO: fails if unused bibfiles
E15: Invalid expression: split(glob(b:livepreview_buf_data['root_dir'] . '/**/*.bib'))     " TODO: fails if unused bibfiles
line   90:
E121: Undefined variable: l:bib_files
E116: Invalid arguments for function len(l:bib_files) > 0
E15: Invalid expression: len(l:bib_files) > 0
line  116:
E121: Undefined variable: l:tmp_out_file
E116: Invalid arguments for function <SNR>25_RunInBackground
line  118:
E186: No previous directory
</details>
```

**Comment by xuhdev** [comment]
@jpchen Can you confirm Python is enabled in your Vim build? What does `:python3 print('Hello')` and `:python print 'hello'` output?

**Comment by jpchen** [comment]
i cant run python 3 in there but `:python print 'hello'` works
