### ISSUE TITLE
Feature Request: ignore compile warnings on demand

### ISSUE THREAD

**Issue by onurhanak** [xuhdev/vim-latex-live-preview#77]
Hi, 
First of all, thank you very much for your work, it has been a critical part of my workflow. I have been using this plugin for quite a while but more often than not some small error or warning that does not effect the generated PDF file in anyway file prevents :LLPStartPreview from compiling correctly. Such errors or warnings can be bypassed when tex file is compiled manually with pdflatex. Is there any way to make :LLPStartPreview to ignore these warnings and force compile the tex file so to say? If not, can this be added to the project? 

Thanks in advance.

**Comment by ACupofAir** [comment]
I annotate the two lines contains "shell_error!=0", which is the line 206 and line 242 in the /plugin/latexlivepreview.vim, then it will ignore the warnings and just preview it.
