### ISSUE TITLE
OS X LLPStartPreview Bugging Vim

### ISSUE THREAD

**Issue by h0rd3** [xuhdev/vim-latex-live-preview#81]
Greetings.

When I try to compile my .tex document I get Vim frozen so that nothing happens and I have to force quit it.

The steps I have made from the very beginning:

1. Installed Python 3.7.3 from the official website
2. Installed MacVim from a .dwg file from GitHub
3. Manually put latexlivepreview.vim into a manually created .vim folder at "Users"
4. Created .vimrc and put let g:livepreview_previewer = 'open -a Preview' into it as I want my text to be opened in native Preview
5. Created a "test.tex" document via vim and put the following text into it:

\documentclass{article}

\begin{document}

testing
testing
testing

\end{document}

6. Prayed
7. Nothing happened.

The MacVim is 8.1, the settings are here:

+acl               -farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autochdir         +float             +mouse_xterm       +terminal
-autoservername    +folding           +multi_byte        +terminfo
+balloon_eval      -footer            +multi_lang        +termresponse
+balloon_eval_term +fork()            -mzscheme          +textobjects
+browse            +fullscreen        +netbeans_intg     +textprop
++builtin_terms    -gettext           +num64             +timers
+byte_offset       -hangul_input      +odbeditor         +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +transparency
+clientserver      +job               +perl/dyn          +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu

Those are not all of them but as far as I see those are enough.

Please help as I'm trying to set vim and tex together for 4 days now :c

**Comment by xuhdev** [comment]
Is your Vim built with your latest Python 3.7? You can see by running

```
:py3 print(sys.version)
```

**Comment by h0rd3** [comment]
Yeap it is 3.7.3

**Comment by h0rd3** [comment]
The steps I wrote above are actually the only steps I've made. Probably I have missed something. In that case could you please tell me what exactly?

**Comment by David-Fu** [comment]
I've got the same problem with Mac Mojave. When using the command :LLPStartPreview the MacVim just keep processing and never gives the result... I thought that the using it for the first time may need more time to compile and just left it for a night and, unfortunately, nothing happens. I suggest that the bib document has to be created and using in the .tex file, would this be the problem. I also have tried to create a reference.bib and still doesn't work...
<img width="493" alt="Screen Shot 2019-04-22 at 1 15 29 PM" src="https://user-images.githubusercontent.com/49016080/56484157-b7d36280-6500-11e9-898d-3a1397246bc5.png">

**Comment by xuhdev** [comment]
Does Skim work for you? I just want to confirm this is only reproduciable for Preview.

**Comment by David-Fu** [comment]
Unfortunately, I have the same problem while using skim. I guess that It may not be the matter of pdfviewer.

**Comment by ghyatzo** [comment]
Are there any updates on this? I've run into the same issue as  @David-Fu. The windows is just stuck and  LLPStartPreview never returns anything. I actually have to hard kill the terminal window otherwise is frozen.

**Comment by qaisern** [comment]
I also have the same issue
