### ISSUE TITLE
:LLPStartPreview Not a editor command

### ISSUE THREAD

**Issue by David-Fu** [xuhdev/vim-latex-live-preview#83]
## Expected behavior

Tell us what should happen

## Actual behavior
When installed the plugin, the command :LLPStartPreview still don't work.
Tell us what happens instead

## Steps to reproduce

Tell us how it occurs

1.After installed the plugin, I can find the folder for vim-latex-live-preview in the ~/.vim
2.However, the script shows that the plugin is not loaded
3.What's more, the command of the plugin doesn't work as expected
How  can this happen that the folder is already in the .vim but the plug in not been loaded? How can I solve this? Much appreciate.
## System configuration

- **Vim version
With macvim 8.1 and +python3 -python
```bash
# output of `vim --version`
```VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)

- **Platform**:MacOS Mojave

**Comment by luotuoqingshan** [comment]
Do you use pathogen?
```
cd ~/.vim/bundle
git clone this repo
```
This works for me.

**Comment by David-Fu** [comment]
Thx, after using Vundle to install the plugin , it can work as expected. It shows that :LLPStartPreview can be executed as a command.However, while I'm using skim as the pdfviewer, it just stuck at the very beginning, and never opens skim for preview. It seems it's just processing the plugin but doesn't really work. How can I solve this problem?Much appreciate.

**Comment by luotuoqingshan** [comment]
Sorry, I use Preview.

Since you are asking a question unrelated to the title, I suggest you open another issue and maybe many people would like to help you.

Best

**Comment by David-Fu** [comment]
The preview doesn't work too...
And that's exactly what I'm thinking about right now. Thanks.

**Comment by luotuoqingshan** [comment]
wow, mine also couldn't work. I am trying to fix it so I come to issues.

**Comment by phil330d** [comment]
for anyone still having this issue, 
`pip install neovim` (if you use neovim) worked for me
