### ISSUE TITLE
No error and No response after the LLPStartPreview command

### ISSUE THREAD

**Issue by bfly123** [xuhdev/vim-latex-live-preview#84]
LLPStartPreview command exists and there is no error after the command, but no preview open, I have test with evince and mupdf, all have no responses.    

vim 7.4 with python3 
Latex is running as expected.

**Comment by JostBrand** [comment]
#11 Is your file in ~ ?

If yes try another dir

**Comment by mjhough** [comment]
> #11 Is your file in ~ ?
> 
> If yes try another dir

I am also having this issue. I installed debian for a short period and noticed it wasn't working there after I had been using it succesffully in arch. I have now switched back to arch and am still having the problem. I have tested on multiple files that worked previously, none of which are in `~`.

**Comment by bjce** [comment]
Hello

First of all: thank you very much for writing and updating the package!

I face the same issue:
I followed the following steps: 

Add the plugin in the Vundle section of your ~/.vimrc:
```
call vundle#begin()
[...]
" A Vim Plugin for Lively Previewing LaTeX PDF Output
Plugin 'xuhdev/vim-latex-live-preview'
[...]
call vundle#end()
```

Then reload the config and install the new plugin. Run inside vim:

```
:so ~/.vimrc
:PluginInstall
```
Manually Copy plugin/latexlivepreview.vim to ~/.vim/plugin.

But then when running `:LLPStartPreview` inside vim, nothing happens (including no error message)
