### ISSUE TITLE
Find lost tex file

### ISSUE THREAD

**Issue by Yemeen** [xuhdev/vim-latex-live-preview#87]
I closed my tex file without saving, but the live preview of the pdf remains. Does live-preview save a copy of the tex file somewhere or am I out of luck?

**Comment by xuhdev** [comment]
In your system temporary directory (e.g., `/tmp` or `/tmp/your_user_name`), there might be a directory named `vim-latex-live-preview-xxxxx`. Your file might be in that directory. If not, I'm afraid you are out of luck. (Don't reboot! Otherwise it may be gone forever)

**Comment by Yemeen** [comment]
Even in Macos? When viewing it on skim I noticed this 
<img width="419" alt="Screen Shot 2019-09-30 at 5 17 35 PM" src="https://user-images.githubusercontent.com/11223834/65917795-341e7b80-e3a6-11e9-9e04-0ff85645b387.png">.

But when searching through tmp, I can find no such folder. Would putting it to sleep clear the tmp files?

**Comment by xuhdev** [comment]
I'm not sure -- tmp files can be cleared regularly whenever the OS feels beneficial.

**Comment by Yemeen** [comment]
Found it! For reference this was the folder it was in for anyone who doesn't save often like me.
<img width="790" alt="Screen Shot 2019-09-30 at 5 40 16 PM" src="https://user-images.githubusercontent.com/11223834/65919104-61205d80-e3a9-11e9-9054-7bd5c7c34e28.png">
