### ISSUE TITLE
Compatibility with neovim

### ISSUE THREAD

**Issue by Msouza91** [xuhdev/vim-latex-live-preview#98]
## Preface
`:echo has('python')` returns 1
I use CoC and vim-plug, both rely on python to function and they do, what am I missing? I've even set the `g:python3_host_prog = '/usr/bin/python3'` variable in my vimrc to see if it would enable properly.

## Expected behavior

Install the plugin and be able to start preview with LLPStartPreview

## Actual behavior
Not an editor command error for LLPStartPreview

## Steps to reproduce

Tell us how it occurs

1. Install neovim
2. Install python-neovim or python3-neovim
3. Install vim-latex-live-preview and try to use it

## System configuration

- **Vim version**:

```bash
# output of `vim --version`
NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-Bljd1N/neovim-0.3.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-Bljd1N/neovim-0.3.8/build/config -I/build/neovim-Bljd1N/neovim-0.3.8/src -I/usr/include -I/build/neovim-Bljd1N/neovim-0.3.8/build/src/nvim/auto -I/build/neovim-Bljd1N/neovim-0.3.8/build/include
Compilado por team+vim@tracker.debian.org

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

- **Platform**:
Ubuntu 19.10

**Comment by vglinden** [comment]
I use Arch Linux and I don't have any problem using the same set-up as you.
This plugin uses python2, are you sure you have py2 in your system?
